"""Emit the build settings of the interpreter running this script, as a makefile.

Used by the backends that embed Python (pytest, pyserial).  Run with the
interpreter you intend to embed -- external/venv/bin/python when it was
bootstrapped with uv, or a system python3.14t when that one is free-threaded.
"""

import os
import sys
import sysconfig

import nanobind

nb_dir = os.path.dirname(os.path.abspath(nanobind.__file__))
libdir = sysconfig.get_config_var("LIBDIR")
ldlibrary = sysconfig.get_config_var("LDLIBRARY")  # e.g. libpython3.14t.so

# strip the leading "lib" and the extension to get the -l argument
stem = ldlibrary[3:] if ldlibrary.startswith("lib") else ldlibrary
stem = stem.split(".so")[0].split(".a")[0]

free_threaded = bool(sysconfig.get_config_var("Py_GIL_DISABLED"))

print("# generated by tools/pyconfig.py -- do not edit")
print("PY_HOME    :=", sys.base_prefix)
print("PY_INCLUDE :=", sysconfig.get_config_var("INCLUDEPY"))
print("PY_LIBDIR  :=", libdir)
print("PY_LIB     :=", stem)
print("PY_VERSION :=", sysconfig.get_python_version())
print("PY_EXT_SUFFIX :=", sysconfig.get_config_var("EXT_SUFFIX"))
print("PY_FREE_THREADED :=", "1" if free_threaded else "0")
print("PY_SITE    :=", sysconfig.get_path("purelib"))
print("NB_DIR     :=", nb_dir)
print("NB_VERSION :=", nanobind.__version__)

# Ready-made flag sets, so a backend makefile does not have to reassemble them.
# NB_FREE_THREADED makes nanobind emit modules that declare Py_MOD_GIL_NOT_USED;
# without it importing the bindings would silently re-enable the GIL and every
# Python module in the job would serialise.
includes = [
    sysconfig.get_config_var("INCLUDEPY"),
    os.path.join(nb_dir, "include"),
    os.path.join(nb_dir, "ext", "robin_map", "include"),
]
cxxflags = ["-isystem " + path for path in includes]
if free_threaded:
    cxxflags.append("-DNB_FREE_THREADED")
print("PY_CXXFLAGS :=", " ".join(cxxflags))
print("PY_LDFLAGS :=", f"-L{libdir} -l{stem} -Wl,-rpath,{libdir}")
print("NB_COMBINED :=", os.path.join(nb_dir, "src", "nb_combined.cpp"))
