alpakatest_EXTERNAL_DEPENDS := TBB ALPAKA BOOST
ifdef CUDA_BASE
alpakatest_EXTERNAL_DEPENDS += CUDA
endif
Test1_DEPENDS := Framework DataFormats AlpakaCore
Test2_DEPENDS := Framework DataFormats AlpakaCore
