---
MainSourceFile:  '/data/user/fwyzard/pixeltrack-standalone/src/oneapitest/CUDACore/ProductBase.h'
Replacements:
  - FilePath:        '/data/user/fwyzard/pixeltrack-standalone/src/cudatest/CUDACore/ProductBase.h'
    Offset:          91
    Length:          0
    ReplacementText: '#include <CL/sycl.hpp>
#include <dpct/dpct.hpp>
'
  - FilePath:        '/data/user/fwyzard/pixeltrack-standalone/src/cudatest/CUDACore/ProductBase.h'
    Offset:          1548
    Length:          12
    ReplacementText: 'sycl::queue *'
  - FilePath:        '/data/user/fwyzard/pixeltrack-standalone/src/cudatest/CUDACore/ProductBase.h'
    Offset:          1867
    Length:          11
    ReplacementText: 'sycl::event'
...
