alpaka_EXTERNAL_DEPENDS := TBB EIGEN ALPAKA BOOST
BeamSpotProducer_DEPENDS := Framework AlpakaCore AlpakaDataFormats DataFormats
PixelTriplets_DEPENDS := Framework AlpakaCore AlpakaDataFormats
PixelVertexFinding_DEPENDS := Framework AlpakaCore AlpakaDataFormats DataFormats CondFormats
SiPixelClusterizer_DEPENDS := Framework AlpakaCore AlpakaDataFormats DataFormats CondFormats
SiPixelRecHits_DEPENDS := Framework AlpakaCore AlpakaDataFormats DataFormats CondFormats
Validation_DEPENDS := Framework AlpakaCore AlpakaDataFormats DataFormats
