#ifndef RecoLocalTracker_SiPixelClusterizer_plugins_gpuClusteringConstants_h
#define RecoLocalTracker_SiPixelClusterizer_plugins_gpuClusteringConstants_h

#include "CUDADataFormats/gpuClusteringConstants.h"

#endif  // RecoLocalTracker_SiPixelClusterizer_plugins_gpuClusteringConstants_h
