kokkos_EXTERNAL_DEPENDS := TBB CUDA KOKKOS EIGEN
BeamSpotProducer_DEPENDS := Framework KokkosCore KokkosDataFormats DataFormats
PixelTriplets_DEPENDS := Framework KokkosCore KokkosDataFormats
PixelVertexFinding_DEPENDS := Framework KokkosCore KokkosDataFormats DataFormats CondFormats
SiPixelClusterizer_DEPENDS := Framework KokkosCore KokkosDataFormats DataFormats CondFormats
SiPixelRecHits_DEPENDS := Framework KokkosCore KokkosDataFormats DataFormats CondFormats
