kokkos_EXTERNAL_DEPENDS := TBB CUDA KOKKOS
BeamSpotProducer_DEPENDS := Framework KokkosCore KokkosDataFormats DataFormats CondFormats
PixelVertexFinding_DEPENDS := Framework KokkosCore KokkosDataFormats DataFormats CondFormats
SiPixelClusterizer_DEPENDS := Framework KokkosCore KokkosDataFormats DataFormats CondFormats
SiPixelRecHits_DEPENDS := Framework KokkosCore KokkosDataFormats DataFormats CondFormats
