cuda_EXTERNAL_DEPENDS := TBB CUDA CUB
BeamSpotProducer_DEPENDS := Framework CUDACore CUDADataFormats
CUDACore_DEPENDS := Framework
CUDADataFormats_DEPENDS := CUDACore DataFormats
CondFormats_DEPENDS := CUDACore
SiPixelClusterizer_DEPENDS := Framework CUDACore CUDADataFormats CondFormats DataFormats
SiPixelRawToDigi_DEPENDS := Framework CUDACore CUDADataFormats CondFormats DataFormats
SiPixelRecHits_DEPENDS := Framework CUDACore CUDADataFormats CondFormats
