// nanobind bindings exposing edm::Event and edm::ProductRegistry to Python.
//
// Compiled into libFramework.so; PyInit_edm_core() is registered with
// PyImport_AppendInittab() before the interpreter starts, so `import edm_core`
// works without any .so on disk.
//
// Nothing here knows about any product type.  Everything that does -- the class
// bindings and the get/emplace dispatch -- is generated from the ROOT
// dictionaries by tools/generate_bindings.C and reached through the three
// declarations below.  That is what lets this file, and the whole Framework
// directory, be identical in every backend that embeds Python.
//
//     token = registry.consumes("<C++ product type>", "<producing module>")
//     out   = registry.produces("<C++ product type>")
//     src   = event.get(token)
//     dst   = event.allocate(out)      # storage to fill in place
//     event.put(out, value)            # a copy of a product you already have
//     event.emplace(out, *values)      # built from Python values, moved in

#include <string>
#include <vector>

#include <nanobind/nanobind.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/vector.h>

#include "Framework/Event.h"
#include "Framework/EventSetup.h"
#include "Framework/PayloadTypes.h"
#include "Framework/ProductRegistry.h"

namespace nb = nanobind;

// Generated by tools/generate_bindings.C.
void registerReflectedBindings(nb::module_& m);
nb::object reflectedGet(nb::handle self, edm::Event& event, edm::EDGetToken const& token);
nb::object reflectedAllocate(nb::handle self, edm::Event& event, edm::EDPutToken const& token,
                             nb::args args);
nb::object reflectedPut(edm::Event& event, edm::EDPutToken const& token, nb::handle value);
nb::object reflectedEmplace(edm::Event& event, edm::EDPutToken const& token, nb::args args);
nb::object reflectedESGet(nb::handle self, edm::EventSetup const& eventSetup, std::string const& typeName);

namespace {
  edm::Event& unwrap(nb::handle self) { return nb::cast<edm::Event&>(self); }
}  // namespace

NB_MODULE(edm_core, m) {
  m.doc() = "Access to the C++ edm::Event and edm::ProductRegistry from Python.";

  // Tokens.  A Python module gets these back from the ProductRegistry it is
  // constructed against, and they are the only way to reach a product.
  nb::class_<edm::EDGetToken>(m, "GetToken")
      .def_prop_ro("index", &edm::EDGetToken::index)
      .def_prop_ro("type", &edm::EDGetToken::typeName)
      .def("__repr__", [](edm::EDGetToken const& t) {
        return "<GetToken #" + std::to_string(t.index()) + " of " + t.typeName() + ">";
      });

  nb::class_<edm::EDPutToken>(m, "PutToken")
      .def_prop_ro("index", &edm::EDPutToken::index)
      .def_prop_ro("type", &edm::EDPutToken::typeName)
      .def("__repr__", [](edm::EDPutToken const& t) {
        return "<PutToken #" + std::to_string(t.index()) + " of " + t.typeName() + ">";
      });

  // Handed to a Python module's factory, which declares against it exactly as
  // a C++ module's constructor does:
  //
  //     class Module:
  //         def __init__(self, config, registry):
  //             self.input = registry.consumes(TYPE, config["input"])
  //             self.output = registry.produces(TYPE)
  nb::class_<edm::ProductRegistry>(m, "ProductRegistry",
                                   "Where a module declares what it reads and writes.")
      .def(
          "consumes",
          [](edm::ProductRegistry& self, std::string const& type, std::string const& label) {
            return self.consumes(type, label);
          },
          nb::arg("type"), nb::arg("label"),
          "Declare a read of the product of C++ type `type` published by module `label`.")
      .def(
          "produces",
          [](edm::ProductRegistry& self, std::string const& type) { return self.produces(type); },
          nb::arg("type"),
          "Declare that this module publishes a product of C++ type `type` under its own label.");

  m.def(
      "types", [] { return edm::payloadTypeNames(); },
      "The C++ product types this job can move across the boundary, by name.");

  nb::class_<edm::Event>(m, "Event", "The products of one event.")
      .def_prop_ro("eventID", &edm::Event::eventID, "Index of this event.")
      .def_prop_ro("streamID", &edm::Event::streamID, "Index of the stream processing it.")
      .def(
          "get",
          [](nb::handle self, edm::EDGetToken const& token) {
            return reflectedGet(self, unwrap(self), token);
          },
          nb::arg("token"), "The product the token names, by reference; nothing is copied.")
      .def(
          "allocate",
          [](nb::handle self, edm::EDPutToken const& token, nb::args args) {
            return reflectedAllocate(self, unwrap(self), token, args);
          },
          "Construct the product the token names inside the Event, and return it by "
          "reference so the module fills it in place rather than building something that "
          "then has to be copied in.  Nothing is set: a product that needs sizing or "
          "wiring before it can be filled takes those arguments here.")
      .def(
          "put",
          [](nb::handle self, edm::EDPutToken const& token, nb::handle value) {
            return reflectedPut(unwrap(self), token, value);
          },
          nb::arg("token"), nb::arg("value"),
          "Copy `value` into the Event as the product the token names.  `value` has to be "
          "one already -- use emplace() to build one from Python values.  Returns nothing: "
          "what is in the Event is a copy, and a name bound to the argument is not a "
          "reference to it.")
      .def(
          "emplace",
          [](nb::handle self, edm::EDPutToken const& token, nb::args args) {
            return reflectedEmplace(unwrap(self), token, args);
          },
          "Build the product the token names from these values and move it into the Event. "
          "Returns nothing: the product is complete, and there is nothing left to fill.");

  // The EventSetup, which holds what does not change event by event.  It is
  // keyed by type and has no tokens -- a C++ module writes es.get<T>() with no
  // prior declaration -- so a Python module names the type the same way.
  //
  // The reference handed out is not const, because nanobind has no per-instance
  // constness to express that with.  An EventSetup product is shared by every
  // stream, so writing to one from Python would corrupt the whole job; the
  // Event's products are at least confined to one event.
  nb::class_<edm::EventSetup>(m, "EventSetup", "What does not change from event to event.")
      .def(
          "get",
          [](nb::handle self, std::string const& type) {
            return reflectedESGet(self, nb::cast<edm::EventSetup const&>(self), type);
          },
          nb::arg("type"), "The EventSetup product of C++ type `type`, by reference.");

  // Every product type, and everything reachable from one.
  registerReflectedBindings(m);
}
