kokkostest_EXTERNAL_DEPENDS := TBB KOKKOS BOOST BACKTRACE
ifeq ($(KOKKOS_DEVICE_PARALLEL),CUDA)
  kokkostest_EXTERNAL_DEPENDS += CUDA
else ifeq ($(KOKKOS_DEVICE_PARALLEL),HIP)
  kokkostest_EXTERNAL_DEPENDS += ROCM
endif
KokkosCore_DEPENDS := Framework
Test1_DEPENDS := Framework DataFormats KokkosCore CUDACore
Test2_DEPENDS := Framework KokkosCore CUDACore
